# Generated by Django 4.2.4 on 2023-08-18 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
